version: "3.9"

services:
  # -------------------------
  # FunASR 服务
  # -------------------------
  funasr:
    image: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.7
    container_name: funasr
    command: >
      bash -c "cd FunASR/runtime && nohup bash run_server.sh
      --download-model-dir /workspace/models
      --model-dir damo/SenseVoiceSmall-onnx
      --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx
      --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst
      --itn-dir thuduj12/fst_itn_zh
      --decoder-thread-num 8
      --model-thread-num 2
      --hotword /workspace/models/hotwords.txt > log.out 2>&1 & sleep infinity"
    volumes:
      - ../funasr_resources/models:/workspace/models
    ports:
      - "10095:10095"
    networks:
      - asr_net

  # -------------------------
  # Gateway API 层（开发模式）
  # -------------------------
  asr_gateway_dev:
    profiles: [ "dev" ]
    image: python:3.10-slim
    container_name: asr_gateway_dev
    working_dir: /app
    volumes:
      - ../gateway_app:/app/gateway_app        # 挂载本地代码
      - ../requirements.txt:/app/requirements.txt
      - ./logs:/var/log/asr                   # 日志挂载到 infra/logs
    command: >
      bash -c "pip install --no-cache-dir -r /app/requirements.txt &&
               uvicorn gateway_app.main:app --host 0.0.0.0 --port 22800  --reload > /var/log/asr/gateway_dev.log 2>&1"
    environment:
      - FUNASR_SERVER=wss://funasr:10095
    ports:
      - "22800:22800"
    depends_on:
      - funasr
    networks:
      - asr_net

  # -------------------------
  # Gateway API 层（生产模式）
  # -------------------------
  asr_gateway:
    profiles: [ "prod" ]
    build:
      context: .
      dockerfile: gateway_app/Dockerfile
    container_name: asr_gateway
    environment:
      - FUNASR_SERVER=wss://funasr:10095
    volumes:
      - ./infra/logs:/var/log/asr
    command: >
      bash -c "uvicorn gateway_app.main:app --host 0.0.0.0 --port 22800 > /var/log/asr/gateway.log 2>&1"
    expose:
      - "22800"
    depends_on:
      - funasr
    networks:
      - asr_net

  # -------------------------
  # Nginx 负载均衡
  # -------------------------
  nginx_dev:
    profiles: [ "dev" ]
    image: nginx:alpine
    container_name: asr_nginx_dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - asr_gateway_dev

  nginx:
    profiles: [ "prod" ]
    image: nginx:alpine
    container_name: asr_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - asr_gateway

networks:
  asr_net:
    driver: bridge